<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon></ApplicationIcon>
      <AssemblyName>AAFSerialCaptureApp</AssemblyName>
      <RootNamespace>AAFSerialCaptureApp</RootNamespace>
      <Product>AAF Serial Capture App</Product>
      <Title>AAF Serial Capture App</Title>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>

</Project>
